config/routes.rb
Rails.application.routes.draw do
  root 'departure_boards#index'

  resources :departure_boards, only: [:index, :show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departure_boards_controller.rb
class DepartureBoardsController < ApplicationController
  before_action :set_departure_board, only: [:show]

  ::DepartureBoard # This kludge is required in Heroku (but not localhost) for some reason

  def index
    @origins = DepartureBoard.origins
  end

  private
    def set_departure_board
      @departure_board = DepartureBoard.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departure_boards_helper.rb
module DepartureBoardsHelper

  MAX_DISPLAYED_DEPARTURES = 12

  def epoch_to_eastern_time(epoch_time)
    # config.time_zone = "Eastern Time (US & Canada)"
    Time.at(epoch_time.to_i).in_time_zone("Eastern Time (US & Canada)").strftime( "%l:%M %p" )
  end

  def track_num(track_num)
    track_num ? track_num : "TBD"
  end

  def sort_limit(departures)
    departures.sort {|d1, d2| d1.scheduledtime <=> d2.scheduledtime}[0...MAX_DISPLAYED_DEPARTURES]
  end
end

app/views/departure_boards/_departure.html.erb
<tr class="text">
  <td><%= departure.carrier.upcase %></td>
  <td class="rightalign scheduled_time"><%= epoch_to_eastern_time(departure.scheduledtime) %></td>
  <td><%= departure.destination.upcase %></td>
  <td><%= departure.trip %></td>
  <td class="leftalign"><%= track_num(departure.track) %></td>
  <td class="statustext"><%= departure.status.upcase %></td>
</tr>

app/views/departure_boards/index.html.erb
<div class="departure_boards">

  <h1>Departure Boards</h1>

  <table>
    <thead>
    <tr>
      <th>Station</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
      <% @origins.sort.each do |origin| %>
        <tr>
          <td><%= origin %></td>
          <td><%= link_to 'Show Departures', "#{departure_boards_url}/#{origin}" %></td>
        </tr>
      <% end %>
    </tbody>
</table>

</div>

app/views/departure_boards/show.html.erb
<div class="content_wrapper">
  <div class="departure_board">
    <h1 class="heading"><%= params[:id].upcase %> TRAIN INFORMATION</h1>

    <table>
      <thead>
        <col class="tbl-col">
        <col class="tbl-col">
        <col class="tbl-col-dest">
        <col class="tbl-col">
        <col class="tbl-col">
        <col class="tbl-col">
        <col class="tbl-col">

      </thead>
      <tr class="subheading">
        <th>CARRIER</th>
        <th>TIME</th>
        <th>DESTINATION</th>
        <th>TRAIN#</th>
        <th>TRACK#</th>
        <th>STATUS</th>
      </tr>
      <%= render partial: "departure", collection: sort_limit(@departure_board), as: :departure %>
    </table>
  </div>

  <div class="backlink">
    <%= link_to 'Back to Departure Boards List', departure_boards_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartureBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!--*** TODO: Move this CSS into a stylesheet ***-->
    <style>
      .content_wrapper {
        width: 900px;
        margin: auto;
        text-align: left
      }

      .departure_boards {
        font-family: "Arial";
      }

      .departure_board table {
        margin: 18px;
      }

      .departure_board {
        padding: 12px;
        background-color: black;
      }

      .backlink {
        margin-top: 18px
      }

      .heading {
        color: #9c9c9c;
        text-align: center;
        font-family: "Courier New";
        font-size: 1.2em;
      }

      .subheading {
        color: #9c9c9c;
        font-family: "Arial";
        font-size: 0.9em;
      }

      .text {
        color: #fffe90;
        font-family: "Courier New";
        font-size: 1em;
        font-weight: bold;
      }

      .statustext {
        color: #e0ff99;
        font-family: "Courier New";
        font-weight: bold;
      }

      .tbl-col {
        width:12%;
      }

      .tbl-col-dest {
        width:38%;
      }

      .scheduled_time {
        padding-right: 16px;
      }

      .leftalign {
        text-align: left;
      }

      .rightalign {
        text-align: right;
      }

    </style>

  </head>

  <body>
    <%= yield %>
  </body>
</html>